### ISSUE TITLE
Link to refactoring resource broken

### ISSUE THREAD

**Issue by jamesmbaazam** [INTERSECT-training/intersect-training.github.io#54]
Hi, the link to the one item under "refactoring" is broken. The current link is https://wordpress.cels.anl.gov/atpesc/files/2020/08/ATPESC-2020-Track-7-Talk-7-Dubey-Refactoring.pdf

**Comment by JeffCarver** [comment]
https://github.com/INTERSECT-training/intersect-training.github.io/pull/55 fixes this issue

**Comment by cosden** [comment]
Thank you, @jamesmbaazam!

**Comment by jamesmbaazam** [comment]
It's a pleasure. Thank you for putting this material together. Really useful.
